package={name='view', version='0.0.0', edition='2021', default-run='main'}
bin=[{name='main', path='main.rs'}]
[dependencies]
fehler='*'
vector={git='https://github.com/Matthias-Fauconneau/vector'}
xy={git='https://github.com/Matthias-Fauconneau/xy'}
ui={git='https://github.com/Matthias-Fauconneau/ui'}
memmap={version='*', package='memmap2'}
owning-ref={package='owning_ref', version = "*"}
bytemuck={version="*", features = ['extern_crate_alloc']}
image={git='https://github.com/Matthias-Fauconneau/image'}
rayon="*"
tiff='*'
las= "*"

[patch.crates-io]
ash-window={git='https://github.com/Matthias-Fauconneau/ash'}
ash={git='https://github.com/Matthias-Fauconneau/ash'}
tiff={path='../image-tiff'}
jpeg-decoder={path="../jpeg-decoder"}
[patch.'https://github.com/Matthias-Fauconneau/image']
image={path='../image'}

[profile.dev]
opt-level = 3
overflow-checks = false