package={name='las', version='0.0.0', edition='2021', default-run='main'}
bin=[{name='main', path='main.rs'}]
[dependencies]
fehler='*'
vector={git='https://github.com/Matthias-Fauconneau/vector'}
xy={git='https://github.com/Matthias-Fauconneau/xy'}
ui={git='https://github.com/Matthias-Fauconneau/ui'}
memmap={version='*', package='memmap2'}
owning-ref={package='owning_ref', version = "*"}
bytemuck="*"
image={git='https://github.com/Matthias-Fauconneau/image'}

[patch.crates-io]
ash-window={git='https://github.com/Matthias-Fauconneau/ash'}
ash={git='https://github.com/Matthias-Fauconneau/ash'}

[profile.dev]
opt-level = 1
overflow-checks = false